In [10]:
import pandas as pd

In [11]:
#import train and labels
def getData(filename):
    df=pd.read_csv(filename,header=None)
    train_df=df.iloc[:,:-1]
    label=df.iloc[:,-1]
    return train_df, label

In [12]:
import numpy as np

#implement distance cal
def euclidean(p1, p2):
    dist = np.sqrt(np.sum((p1 - p2) ** 2))
    return dist

def manhattan(p1,p2):
    dist = np.sum(np.abs(p1-p2))
    return dist

In [13]:
from scipy.stats import mode
from collections import Counter

def majority_vote(labels):
    vote_counts = Counter(labels)
    winner, winner_count = vote_counts.most_common(1)[0]
    return winner


def predict(x_train, y, x_input, k):
    op_labels = []
    for index_input, row_input in x_input.iterrows():
        distances = []
        
        for index_train, row_train in x_train.iterrows():
            distance = euclidean(row_train, row_input)
            distances.append((distance,y[index_train]))
            
        distances_df = pd.DataFrame(distances, columns=['distances', 'labels'])
        
        distances_df = distances_df.sort_values(by=['distances'])
        
        distances_df=distances_df.head(k)

        op_labels.append(majority_vote(distances_df['labels']))
    return op_labels

In [16]:
train_file = "data/iris/iris.trn"
test_file = "data/iris/iris.tst"

train_df, train_label = getData(train_file)
test_df, test_label = getData(test_file)

prediction_labels=predict(train_df,train_label,test_df,1)

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(test_label, prediction_labels)
conf_mat = confusion_matrix(test_label, prediction_labels)
print(f"Accuracy: {accuracy}")
print(f"Confusion matrix:\n{conf_mat}")

Accuracy: 0.94
Confusion matrix:
[[17  0  0]
 [ 0 15  0]
 [ 0  3 15]]
