In [27]:
import pandas as pd

In [28]:
from sklearn.model_selection import train_test_split

def getData(filename):
    df=pd.read_csv(filename,header=None)
    train_df=df.iloc[:,:-1]
    label=df.iloc[:,-1]
    return train_df, label
def getData2(filename):
    df=pd.read_csv(filename,delimiter=" ",header=None)
    train_df=df.iloc[:,:-1]
    label=df.iloc[:,-1]
    return train_df, label
def getData3(filename):
    df=pd.read_csv(filename,header=None)
    data_df=df.iloc[:,:-1]
    label=df.iloc[:,-1]
    X_train, X_test, y_train, y_test = train_test_split(data_df, label, test_size=0.2, random_state=0)
    return X_train, X_test, y_train, y_test

In [29]:
import numpy as np

#implement distance cal
def euclidean(p1, p2):
    dist = np.sqrt(np.sum((p1 - p2) ** 2))
    return dist

def manhattan(p1,p2):
    dist = np.sum(np.abs(p1-p2))
    return dist

In [30]:
from collections import Counter

def majority_vote(labels):
    vote_counts = Counter(labels)
    winner, winner_count = vote_counts.most_common(1)[0]
    return winner


def predict(x_train, y, x_input, k):
    op_labels = []
    for index_input, row_input in x_input.iterrows():
        distances = []
        
        for index_train, row_train in x_train.iterrows():
            distance = euclidean(row_train, row_input)
            distances.append((distance,y[index_train]))
            
        distances_df = pd.DataFrame(distances, columns=['distances', 'labels'])
        
        distances_df = distances_df.sort_values(by=['distances'])
        
        distances_df=distances_df.head(k)

        op_labels.append(majority_vote(distances_df['labels']))
    return op_labels

In [37]:
# train_file = "data/fp/fp.trn"
# test_file = "data/fp/fp.tst"

# train_file = "data/iris/iris.trn"
# test_file = "data/iris/iris.tst"

# train_file = "data/letter/let.trn"
# test_file = "data/letter/let.tst"

# train_file = "data/leukemia/ALLAML.trn"
# test_file = "data/leukemia/ALLAML.tst"

train_file = "data/optics/opt.trn"
test_file = "data/optics/opt.tst"

train_df, train_label = getData(train_file)
test_df, test_label = getData(test_file)

prediction_labels=predict(train_df,train_label,test_df,3)

In [38]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(test_label, prediction_labels)
conf_mat = confusion_matrix(test_label, prediction_labels)
print(f"Accuracy: {accuracy}")
print(f"Confusion matrix:\n{conf_mat}")

Accuracy: 0.9788536449638287
Confusion matrix:
[[178   0   0   0   0   0   0   0   0   0]
 [  0 180   0   0   0   0   1   0   1   0]
 [  0   4 173   0   0   0   0   0   0   0]
 [  0   0   0 180   0   0   0   2   1   0]
 [  0   2   0   0 178   0   0   0   1   0]
 [  0   0   0   0   1 179   0   0   0   2]
 [  0   0   0   0   0   0 181   0   0   0]
 [  0   0   0   0   0   0   0 172   1   6]
 [  0   9   0   1   0   0   0   0 162   2]
 [  0   0   0   2   0   1   0   0   1 176]]


In [ ]:
#delimiter = " "
# train_file = "data/fp107/fp107.trn"
# test_file = "data/fp107/fp107.tst" 

train_file = "data/faces/data.trn"
test_file = "data/faces/data.tst"
k=3

train_df, train_label = getData2(train_file)
test_df, test_label = getData2(test_file)
prediction_labels=predict(train_df,train_label,test_df,k)

In [ ]:
# dataset_file = "data/ovarian/ovarian.data"
dataset_file = "data/spam/spam.data"
k=3

train_df, test_df, train_label, test_label = getData3(dataset_file)
prediction_labels=predict(train_df,train_label,test_df,k)